### ISSUE TITLE
at for HashSet

### ISSUE THREAD

**Issue by kozross** [stevenfontanella/microlens#131]
``microlens-mtl`` has ``at`` for ``Set``. However, ``microlens-platform`` lacks ``at`` for ``HashSet``, in a strange asymmetry with ``HashMap`` and ``Map``.

**Comment by neongreen** [comment]
If you contribute a PR, I'll release a new version as soon as possible

**Comment by sjshuck** [comment]
Just thinking out loud.  (I'd like to see an `Iso' (HashSet k) (HashMap k ())` upstream.  And one for ordered `Set` too.)

Anyway, let me know if you're interested in a PR (that doesn't do it this way but merely copies `lens`' implementation).

**Comment by stevenfontanella** [comment]
Released [microlens-platform 0.4.3.5](https://hackage.haskell.org/package/microlens-platform-0.4.3.5) with #175 included. Thanks @crumbtoo!
