### ISSUE TITLE
Add _Show

### ISSUE THREAD

**Issue by sjshuck** [stevenfontanella/microlens#143]
https://hackage.haskell.org/package/lens/docs/Control-Lens-Combinators.html#v:_Show

Obviously the type would have to be changed to

```haskell
(Read a, Show a) => Traversal' String a
```

Additionally, the name seems backwards if it's going to be a Traversal:  the value is being viewed as _read_ rather than as _shown_.  But oh well, it's a Prism, it looks like a constructor if you squint, and it's been in `lens` for years.

I personally use this one quite a bit.  Happy to toss it in if you approve of the idea.

**Comment by kana-sama** [comment]
btw it is very easy to implement

```haskell
import Text.Read (readMaybe)

_Show :: (Show a, Read a) => Traversal' String a
_Show next source =
  case readMaybe source of
    Just value -> show <$> next value
    Nothing -> pure source
```

**Comment by sjshuck** [comment]
@kana-sama Here's a use case: https://hackage.haskell.org/package/pcre2-1.1.4/docs/Text-Regex-Pcre2.html#v:_regex

**Comment by neongreen** [comment]
I will accept a PR that adds this (the traversal must also have haddocks on par with other microlens docs).

**Comment by sjshuck** [comment]
https://github.com/sjshuck/microlens/commit/7a816f116f254c56820972fbbaefb4d4b7b57a53

I didn't bump versions because of another couple functions I remembered to ask about that you might want to include in the same release, if at all (see above issue).
