### ISSUE TITLE
Add worded and lined

### ISSUE THREAD

**Issue by sjshuck** [stevenfontanella/microlens#144]
```haskell
worded, lined :: Traversal' String String
```

Same ballpark as #143.  These are improper as documented [here](https://hackage.haskell.org/package/lens-4.19.2/docs/Control-Lens-Combinators.html#v:worded).

**Comment by neongreen** [comment]
Same ballpark = you also use them "quite a bit"? If yes, they can also be included. Just turn your branch into a PR.

**Comment by sjshuck** [comment]
OK thanks, I'll include all 3 functions in the same PR.

Same ballpark = they're all improper `Traversal'`s focusing from `String`s.  And yeah I do use them.
