### ISSUE TITLE
microlens-platform: support hashable 1.5.0.0, get back in stackage

### ISSUE THREAD

**Issue by simonmichael** [stevenfontanella/microlens#183]
Could we have a hackage revision raising the hashable upper bound to allow 1.5.0.0:
```
hashable >=1.1.2.3 && <1.6
```

I confirm that microlens-platform builds with the newer hashable.

This will allow microlens-platform and packages depending on it (like hledger-ui) back into stackage nightly.

**Comment by stevenfontanella** [comment]
Thanks for reporting, I'll take a look and create a release this weekend.

**Comment by stevenfontanella** [comment]
Looks like #182 will address this. I'll follow up there.

**Comment by stevenfontanella** [comment]
Thanks! I’ll create a release later tonight.

**Comment by simonmichael** [comment]
Thank you very much!
